<a href="https://colab.research.google.com/github/GryffindorafAviator/NormedSpaceCourses/blob/main/1stnn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import torch.nn as nn
from torch.nn import functional as F

In [16]:
# Build dataset
torch.manual_seed(111)
X = torch.rand((500, 20), dtype=torch.float32)
y = torch.randint(low=0, high=3, size=(500, 1), dtype=torch.float32)

In [17]:
# Define neural network with nn.Modele
class Model(nn.Module):
  def __init__(self, in_features=10, out_features=2):
    super(Model, self).__init__()
    self.linear1 = nn.Linear(in_features, 13, bias=True)
    self.linear2 = nn.Linear(13, 8, bias=True)
    self.output = nn.Linear(8, out_features, bias=True)

  def forward(self, x):
    z1 = self.linear1(x)
    sigma1 = torch.relu(z1)
    z2 = self.linear2(sigma1)
    sigma2 = torch.sigmoid(z2)
    z3 = self.output(sigma2)
    sigma3 = F.softmax(z3, dim=1)
    return sigma3

In [18]:
input_ = X.shape[1]
output_ = len(y.unique())

In [19]:
# Instantiate neural network
torch.manual_seed(111)
net = Model(input_, output_)

In [20]:
# Foward propagation
net(X)
# net.forward(X)

tensor([[0.4587, 0.2204, 0.3209],
        [0.4486, 0.2214, 0.3300],
        [0.4460, 0.2239, 0.3301],
        ...,
        [0.4556, 0.2196, 0.3248],
        [0.4533, 0.2212, 0.3255],
        [0.4514, 0.2184, 0.3302]], grad_fn=<SoftmaxBackward0>)

In [21]:
# Check the output labels
sigma = net.forward(X)
sigma.max(axis=1)

torch.return_types.max(
values=tensor([0.4587, 0.4486, 0.4460, 0.4612, 0.4567, 0.4446, 0.4659, 0.4521, 0.4569,
        0.4520, 0.4537, 0.4461, 0.4542, 0.4517, 0.4513, 0.4547, 0.4481, 0.4526,
        0.4500, 0.4497, 0.4486, 0.4535, 0.4520, 0.4565, 0.4529, 0.4526, 0.4559,
        0.4602, 0.4592, 0.4444, 0.4583, 0.4598, 0.4596, 0.4598, 0.4613, 0.4519,
        0.4533, 0.4548, 0.4439, 0.4540, 0.4514, 0.4479, 0.4538, 0.4510, 0.4463,
        0.4462, 0.4554, 0.4503, 0.4605, 0.4563, 0.4548, 0.4489, 0.4487, 0.4574,
        0.4603, 0.4495, 0.4524, 0.4500, 0.4461, 0.4455, 0.4485, 0.4509, 0.4497,
        0.4532, 0.4495, 0.4503, 0.4551, 0.4539, 0.4495, 0.4498, 0.4511, 0.4538,
        0.4526, 0.4472, 0.4495, 0.4569, 0.4592, 0.4475, 0.4510, 0.4526, 0.4563,
        0.4487, 0.4521, 0.4533, 0.4569, 0.4458, 0.4512, 0.4531, 0.4509, 0.4551,
        0.4539, 0.4508, 0.4523, 0.4548, 0.4602, 0.4559, 0.4560, 0.4471, 0.4518,
        0.4548, 0.4570, 0.4511, 0.4450, 0.4473, 0.4616, 0.4543, 0.4507, 0.4527,
        0

In [23]:
# Check the weights and biases for layer 1
net.linear1.weight
net.linear1.bias

Parameter containing:
tensor([ 0.1188, -0.1312, -0.0269,  0.1918, -0.1392,  0.0383,  0.1376, -0.1074,
        -0.1595, -0.1478,  0.1601,  0.1392,  0.0550], requires_grad=True)

In [24]:
# Check the weights and biases for layer 2
net.linear2.weight
net.linear2.bias

Parameter containing:
tensor([-0.0305, -0.1496, -0.1739,  0.0626, -0.2284, -0.1108,  0.0877,  0.1331],
       requires_grad=True)

In [25]:
# Check the weights and biases for output layer
net.output.weight
net.output.bias

Parameter containing:
tensor([ 0.0307, -0.3067, -0.1574], requires_grad=True)